id: P49737977
initial_creation_type: input
source_metadata:
  Title: Hetubinduṭīkā
  Editor: Pandit S. Sanghavi and Muni Shri Jinavijayaji
  Publisher: Oriental Institute
  Place of Publication: Baroda
  Year: '1949'
  Hetoḥ sāmānyanirūpaṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Svabhāvahetunirūpaṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Kāryahetunirūpaṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Anupalabdhihetunirūpaṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:48:25.352536'
last_modified_at: '2022-03-08T16:48:25.352545'
